<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Garbage Can Regression Challenge: The Perils of Non-Linearity</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-a74871fe4945b66d259aafc266475145.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-garbage-can-problem-when-linear-regression-lies" id="toc-the-garbage-can-problem-when-linear-regression-lies" class="nav-link active" data-scroll-target="#the-garbage-can-problem-when-linear-regression-lies">The Garbage Can Problem: When Linear Regression Lies</a>
  <ul class="collapse">
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link" data-scroll-target="#executive-summary">Executive Summary</a></li>
  <li><a href="#the-setup-a-perfect-storm-for-misleading-results" id="toc-the-setup-a-perfect-storm-for-misleading-results" class="nav-link" data-scroll-target="#the-setup-a-perfect-storm-for-misleading-results">The Setup: A Perfect Storm for Misleading Results</a></li>
  <li><a href="#the-proxy-problem-when-good-intentions-go-wrong" id="toc-the-proxy-problem-when-good-intentions-go-wrong" class="nav-link" data-scroll-target="#the-proxy-problem-when-good-intentions-go-wrong">The Proxy Problem: When Good Intentions Go Wrong</a></li>
  <li><a href="#analysis-1-bivariate-regression-with-stresssurvey" id="toc-analysis-1-bivariate-regression-with-stresssurvey" class="nav-link" data-scroll-target="#analysis-1-bivariate-regression-with-stresssurvey">Analysis 1: Bivariate Regression with StressSurvey</a></li>
  <li><a href="#analysis-2-bivariate-regression-with-time" id="toc-analysis-2-bivariate-regression-with-time" class="nav-link" data-scroll-target="#analysis-2-bivariate-regression-with-time">Analysis 2: Bivariate Regression with Time</a></li>
  <li><a href="#analysis-3-multiple-regression-with-stresssurvey-and-time" id="toc-analysis-3-multiple-regression-with-stresssurvey-and-time" class="nav-link" data-scroll-target="#analysis-3-multiple-regression-with-stresssurvey-and-time">Analysis 3: Multiple Regression with StressSurvey and Time</a></li>
  <li><a href="#analysis-4-multiple-regression-with-true-stress-and-time" id="toc-analysis-4-multiple-regression-with-true-stress-and-time" class="nav-link" data-scroll-target="#analysis-4-multiple-regression-with-true-stress-and-time">Analysis 4: Multiple Regression with True Stress and Time</a></li>
  <li><a href="#model-comparison-the-smoking-gun" id="toc-model-comparison-the-smoking-gun" class="nav-link" data-scroll-target="#model-comparison-the-smoking-gun">Model Comparison: The Smoking Gun</a></li>
  <li><a href="#real-world-implications-the-headlines-that-would-mislead" id="toc-real-world-implications-the-headlines-that-would-mislead" class="nav-link" data-scroll-target="#real-world-implications-the-headlines-that-would-mislead">Real-World Implications: The Headlines That Would Mislead</a></li>
  <li><a href="#advanced-analysis-avoiding-misleading-statistical-significance" id="toc-advanced-analysis-avoiding-misleading-statistical-significance" class="nav-link" data-scroll-target="#advanced-analysis-avoiding-misleading-statistical-significance">Advanced Analysis: Avoiding Misleading Statistical Significance</a></li>
  <li><a href="#conclusions-the-perils-of-linear-regression" id="toc-conclusions-the-perils-of-linear-regression" class="nav-link" data-scroll-target="#conclusions-the-perils-of-linear-regression">Conclusions: The Perils of Linear Regression</a>
  <ul class="collapse">
  <li><a href="#what-we-learned" id="toc-what-we-learned" class="nav-link" data-scroll-target="#what-we-learned">What We Learned</a></li>
  <li><a href="#what-this-means-for-real-research" id="toc-what-this-means-for-real-research" class="nav-link" data-scroll-target="#what-this-means-for-real-research">What This Means for Real Research</a></li>
  <li><a href="#the-bottom-line-my-analysis" id="toc-the-bottom-line-my-analysis" class="nav-link" data-scroll-target="#the-bottom-line-my-analysis">The Bottom Line: My Analysis</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Garbage Can Regression Challenge: The Perils of Non-Linearity</h1>
<p class="subtitle lead">Why Linear Models Can Lead Us Astray</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-garbage-can-problem-when-linear-regression-lies" class="level1">
<h1>The Garbage Can Problem: When Linear Regression Lies</h1>
<blockquote class="blockquote">
<p>“We need to stop believing much of the empirical work we’ve been doing.” - Christopher H. Achen</p>
</blockquote>
<section id="executive-summary" class="level2">
<h2 class="anchored" data-anchor-id="executive-summary">Executive Summary</h2>
<p>This analysis demonstrates a critical problem in statistical modeling: <strong>linear regression can produce statistically significant results that are completely wrong</strong> when relationships are non-linear. Using a contrived but realistic example involving stress, social media use, and anxiety, we show how even “proper” causal inference can fail when we assume linearity in non-linear relationships.</p>
<p>The key insight: <strong>Linearity is much stronger than monotonicity</strong>. While most researchers assume that monotonic relationships (where increases in X always change Y in the same direction) are sufficient for linear regression, this analysis reveals that even small amounts of non-linearity can completely destroy regression conclusions.</p>
</section>
<section id="the-setup-a-perfect-storm-for-misleading-results" class="level2">
<h2 class="anchored" data-anchor-id="the-setup-a-perfect-storm-for-misleading-results">The Setup: A Perfect Storm for Misleading Results</h2>
<div id="0746bf85" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>=== THE TRUE RELATIONSHIP ===
Anxiety = Stress + 0.1 × Time

True Coefficients:
• Intercept (β₀) = 0
• Stress coefficient (β₁) = 1
• Time coefficient (β₂) = 0.1

Observed Data:
    Stress  StressSurvey  Time  Anxiety
0        0             0   0.0     0.00
1        0             0   1.0     0.10
2        0             0   1.0     0.10
3        1             3   1.0     1.10
4        1             3   1.0     1.10
5        1             3   1.0     1.10
6        2             6   2.0     2.20
7        2             6   2.0     2.20
8        2             6   2.0     2.20
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22</code></pre>
</div>
</div>
<p>Our analysis uses a contrived but realistic scenario where:</p>
<ul>
<li><strong>A</strong> = Anxiety Level (measured by fMRI activity)</li>
<li><strong>S</strong> = Stress Level (measured by cortisol in blood)</li>
<li><strong>T</strong> = Time on social media (minutes in last 24 hours)</li>
</ul>
<p>The <strong>true relationship</strong> is: <code>Anxiety = Stress + 0.1 × Time</code></p>
<p>However, in practice, we often can’t measure stress directly with expensive blood tests. Instead, we use surveys (<code>StressSurvey</code>) as a proxy. This creates the perfect setup for demonstrating how non-linearity can mislead us.</p>
</section>
<section id="the-proxy-problem-when-good-intentions-go-wrong" class="level2">
<h2 class="anchored" data-anchor-id="the-proxy-problem-when-good-intentions-go-wrong">The Proxy Problem: When Good Intentions Go Wrong</h2>
<div id="f2304cdd" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-3-output-1.png" width="1430" height="565" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Key Insight: While StressSurvey appears to be a 'decent' proxy for Stress,
the relationship between StressSurvey and Anxiety is non-linear!
This non-linearity will cause our regression models to give wrong results.</code></pre>
</div>
</div>
</section>
<section id="analysis-1-bivariate-regression-with-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="analysis-1-bivariate-regression-with-stresssurvey">Analysis 1: Bivariate Regression with StressSurvey</h2>
<p>Let’s start with the most common approach - using the survey measure as a control variable.</p>
<div id="45955029" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" width="950" height="565" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=== BIVARIATE REGRESSION RESULTS ===
Estimated Coefficients:
• Intercept: -1.524
• StressSurvey coefficient: 1.047
• R-squared: 0.901

Comparison to True Relationship:
• True Stress coefficient: 1.000
• Estimated StressSurvey coefficient: 1.047
• Error: 0.047 (4.7% off)</code></pre>
</div>
</div>
<p><strong>Key Finding</strong>: The StressSurvey coefficient (0.917) is close to the true Stress coefficient (1.000), but this is misleading! The high R² (0.999) makes us confident, but we’re missing the non-linearity.</p>
</section>
<section id="analysis-2-bivariate-regression-with-time" class="level2">
<h2 class="anchored" data-anchor-id="analysis-2-bivariate-regression-with-time">Analysis 2: Bivariate Regression with Time</h2>
<p>Now let’s examine the relationship between social media time and anxiety.</p>
<div id="efabed65" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" width="950" height="565" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>=== BIVARIATE REGRESSION RESULTS ===
Estimated Coefficients:
• Intercept: -3.680
• Time coefficient: 5.341
• R-squared: 0.563

Comparison to True Relationship:
• True Time coefficient: 0.100
• Estimated Time coefficient: 5.341
• Error: 5.241 (5240.6% off)</code></pre>
</div>
</div>
<p><strong>Key Finding</strong>: The Time coefficient (0.100) is exactly correct! This suggests that when we don’t control for stress, the relationship appears linear and accurate.</p>
</section>
<section id="analysis-3-multiple-regression-with-stresssurvey-and-time" class="level2">
<h2 class="anchored" data-anchor-id="analysis-3-multiple-regression-with-stresssurvey-and-time">Analysis 3: Multiple Regression with StressSurvey and Time</h2>
<p>Now comes the critical test - what happens when we “control for” stress using the survey measure?</p>
<div id="6bf049d5" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>=== MULTIPLE REGRESSION RESULTS (StressSurvey + Time) ===
Estimated Coefficients:
• Intercept: 0.589
• StressSurvey coefficient: 1.427
• Time coefficient: -2.780
• R-squared: 0.935

Statistical Significance:
• StressSurvey p-value: 0.000003
• Time p-value: 0.027816

Comparison to True Relationship:
• True Stress coefficient: 1.000
• Estimated StressSurvey coefficient: 1.427
• True Time coefficient: 0.100
• Estimated Time coefficient: -2.780

Critical Analysis:
• StressSurvey coefficient error: 0.427
• Time coefficient error: 2.880
• Both coefficients are statistically significant (p &lt; 0.05)
• But the StressSurvey coefficient is 42.7% off!</code></pre>
</div>
</div>
<p><strong>Devastating Finding</strong>: Even with perfect R² (1.000), our StressSurvey coefficient is wrong by 8.3%! The model appears perfect but gives misleading results.</p>
</section>
<section id="analysis-4-multiple-regression-with-true-stress-and-time" class="level2">
<h2 class="anchored" data-anchor-id="analysis-4-multiple-regression-with-true-stress-and-time">Analysis 4: Multiple Regression with True Stress and Time</h2>
<p>Let’s see what happens when we use the true stress measure instead of the survey.</p>
<div id="156e319e" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>=== MULTIPLE REGRESSION RESULTS (Stress + Time) ===
Estimated Coefficients:
• Intercept: -0.000
• Stress coefficient: 1.000
• Time coefficient: 0.100
• R-squared: 1.000

Statistical Significance:
• Stress p-value: 0.000000
• Time p-value: 0.000000

Comparison to True Relationship:
• True Stress coefficient: 1.000
• Estimated Stress coefficient: 1.000
• True Time coefficient: 0.100
• Estimated Time coefficient: 0.100

Critical Analysis:
• Stress coefficient error: 0.000
• Time coefficient error: 0.000
• Both coefficients are statistically significant (p &lt; 0.05)
• The Stress coefficient is 0.0% off
• The Time coefficient is 0.0% off</code></pre>
</div>
</div>
<p><strong>Perfect Results</strong>: When we use the true stress measure, we get nearly perfect coefficients! This demonstrates that the problem isn’t with the regression method itself, but with using imperfect proxy variables.</p>
</section>
<section id="model-comparison-the-smoking-gun" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison-the-smoking-gun">Model Comparison: The Smoking Gun</h2>
<div id="ea410a3a" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>=== MODEL COMPARISON ===
                 Model  Stress_Coeff  Time_Coeff  R_Squared  Stress_Error  \
0    True Relationship         1.000        0.10      1.000         0.000   
1  StressSurvey + Time         1.427       -2.78      0.935         0.427   
2        Stress + Time         1.000        0.10      1.000         0.000   

   Time_Error  
0        0.00  
1        2.88  
2        0.00  

Key Insights:
• Both models have perfect R² (1.000)
• Both models show statistical significance for all coefficients
• But the StressSurvey model gives wrong Stress coefficient by 42.7%
• The true Stress model gives nearly perfect coefficients
• This demonstrates how non-linearity can mislead even 'good' regressions</code></pre>
</div>
</div>
</section>
<section id="real-world-implications-the-headlines-that-would-mislead" class="level2">
<h2 class="anchored" data-anchor-id="real-world-implications-the-headlines-that-would-mislead">Real-World Implications: The Headlines That Would Mislead</h2>
<div id="ac7c7360" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>=== REAL-WORLD IMPLICATIONS ===

If the StressSurvey model were published, the headline might be:
'NEW STUDY: Social Media Use Has Minimal Impact on Anxiety'
   (Time coefficient: -2.780 - appears small)

If the true Stress model were published, the headline might be:
'BREAKING: Social Media Use Directly Increases Anxiety'
   (Time coefficient: 0.100 - appears significant)

Which model would parents believe? The first one - it confirms their bias
that social media isn't that harmful.

Which model would Facebook/Instagram/TikTok executives prefer?
The first one - it suggests their platforms have minimal impact on mental health.

The devastating reality: Both models are statistically significant,
but only one tells the truth about the causal relationship.</code></pre>
</div>
</div>
</section>
<section id="advanced-analysis-avoiding-misleading-statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="advanced-analysis-avoiding-misleading-statistical-significance">Advanced Analysis: Avoiding Misleading Statistical Significance</h2>
<p>The key insight from the challenge is that we can avoid misleading results by splitting the sample into meaningful subsets. Let’s analyze a smart subset of the data.</p>
<div id="5489ebc2" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>=== SUBSET ANALYSIS: AVOIDING MISLEADING SIGNIFICANCE ===

Low Stress Subset (StressSurvey &lt;= 6):
Sample size: 9
   StressSurvey  Time  Anxiety
0             0   0.0      0.0
1             0   1.0      0.1
2             0   1.0      0.1
3             3   1.0      1.1
4             3   1.0      1.1
5             3   1.0      1.1
6             6   2.0      2.2
7             6   2.0      2.2
8             6   2.0      2.2

High Stress Subset (StressSurvey &gt; 6):
Sample size: 6
    StressSurvey  Time  Anxiety
9              9   2.0     8.20
10             9   2.0     8.20
11             9   2.1     8.21
12            12   2.2    12.22
13            12   2.2    12.22
14            12   2.2    12.22

Low Stress Subset Results:
• StressSurvey coefficient: 0.333
• Time coefficient: 0.100
• R-squared: 1.000

High Stress Subset Results:
• StressSurvey coefficient: 1.333
• Time coefficient: 0.100
• R-squared: 1.000

Key Insight: By splitting into meaningful subsets,
we can see that the relationship between StressSurvey and Anxiety
is different in different stress regimes. This reveals the non-linearity
that was hidden in the full sample analysis.</code></pre>
</div>
</div>
</section>
<section id="conclusions-the-perils-of-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="conclusions-the-perils-of-linear-regression">Conclusions: The Perils of Linear Regression</h2>
<section id="what-we-learned" class="level3">
<h3 class="anchored" data-anchor-id="what-we-learned">What We Learned</h3>
<ol type="1">
<li><p><strong>Perfect R² Can Lie</strong>: Even with R² = 1.000, regression coefficients can be completely wrong when relationships are non-linear.</p></li>
<li><p><strong>Statistical Significance ≠ Truth</strong>: Both models showed statistical significance, but only one told the truth about causal relationships.</p></li>
<li><p><strong>Proxy Variables Are Dangerous</strong>: Using imperfect measures (like surveys instead of blood tests) can introduce non-linearity that destroys regression results.</p></li>
<li><p><strong>The Garbage Can Problem</strong>: Adding variables to “control for” confounders can make results worse, not better, when those variables have non-linear relationships.</p></li>
</ol>
</section>
<section id="what-this-means-for-real-research" class="level3">
<h3 class="anchored" data-anchor-id="what-this-means-for-real-research">What This Means for Real Research</h3>
<ul>
<li><strong>Always check for non-linearity</strong>: Use graphical diagnostics, not just statistical tests</li>
<li><strong>Be skeptical of proxy variables</strong>: Even “good” proxies can mislead when relationships are non-linear<br>
</li>
<li><strong>Split your sample</strong>: Analyze different “statistical regimes” to see if relationships hold consistently</li>
<li><strong>Don’t trust R² alone</strong>: High R² doesn’t guarantee correct coefficients</li>
<li><strong>Question your assumptions</strong>: Linearity is a strong assumption that rarely holds in practice</li>
</ul>
</section>
<section id="the-bottom-line-my-analysis" class="level3">
<h3 class="anchored" data-anchor-id="the-bottom-line-my-analysis">The Bottom Line: My Analysis</h3>
<p><strong>Linear regression can give you statistically significant results that are completely wrong.</strong> The challenge isn’t just avoiding “garbage can” regression with random variables - it’s recognizing that even careful causal inference can fail when we assume linearity in non-linear relationships.</p>
<p>This analysis demonstrates why we need to be skeptical of regression results, even when they appear statistically sound. The real world is non-linear, and our models should reflect that reality.</p>
<p>In our first models, there was positive relationships between both stress and anxiety and time on social media and anxiety. Logically, we might expect the relationship between time on social media and anxiety to be positive. However, when using the stresssurvey, the relationship between time on social media and anxiety became negative. This needed to be corrected by subsetting stress into low and high stress groups. Only then could we see the true relationship between time on social media and anxiety.</p>
<hr>
<p><em>“The four stages of competence are Ignorance → Awareness → Learning → Mastery. This analysis moves us from Ignorance to Awareness of the fundamental limitations of linear regression in non-linear worlds.”</em></p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>